### ISSUE TITLE
Point Annotation Incorrect Coordinates

### ISSUE THREAD

**Issue by handenurc** [janfreyberg/ipyannotations#20]
Hi, I'm using Point Annotation widget and it works seamlessly on jupyter notebook. However, when I check keypoint coordinates by saving them on a json file, I figured out that the points are not matched with their corresponding coordinates (i.e. (0,0) top left point is labeled as (160,0)). Other points' values are not accurate either. How can this problem be fixed? Thanks.

**Comment by handenurc** [comment]
Realized that it is related with canvas size. However, I'd like to fit canvas size to the image size for every single image so that I can achieve (i.e. (0,0) value for a sample annotated top left point). Any ideas/help appreciated.

**Comment by janfreyberg** [comment]
Yes, you're absolutely correct that there is a bug in this at the moment.

Changing the canvas size isn't possible for every image, but it is possible to work out what the image coordinate is since the widget stores the "extent" of the image.

I do actually have a fix for this already, but I made the mistake of lumping it into a very large PR that I haven't completely finished yet. In the meantime, I've released a dev version of the package, so you could try:

`pip install --upgrade --pre ipyannotations`

You should then have version 0.3.0.dev0. You will need to change your import statements (`from ipyannotations import PointAnnotator` -> `from ipyannotations.images import PointAnnotator`) but everything else should be the same.

Let me know if this is still an issue afterwards.

**Comment by handenurc** [comment]
Thank you for your quick answer. Could you please explain what you mean by "extent" of the image? Can there be a simple/arithmetic relation to reach the original coordinate somehow (i.e. from (160,0) to (0,0))? I was using default canvas size (700x500 I guess) but again my image sizes vary and I couldn't build any mathematical relationship between image and canvas sizes to save the coordinates accordingly.

So I upgraded the package and changed import line but then I got ''No module named 'ipyannotations.controls''' error while importing PointAnnotator.

**Comment by janfreyberg** [comment]
Yep - what happens when you display an image is:

- the widget determines the image size
- the widget resizes the image to fit within the canvas, if necessary
- the widget displays the image centered on x and y by offsetting it by `(canvas_size - image_size) / 2`

Since the widget then knows what the x / y coordinates of the image are, you can work out how the points correspond to the image, not the canvas:

https://github.com/janfreyberg/ipyannotations/blob/0f629275dfd5e199787d835f38e489dde76303d0/ipyannotations/images/canvases/abstract_canvas.py#L114-L139

If you want to correct points you already collected, you could work it out this way after the fact.
